Makefile, go.mod, go.sum, mods/server/mgmt_key.go, mods/server/mgmt_key_test.go
merge neo-shell client side token+key managment, machbase/neo-shell#8
=> client cert and token authentication

go.mod, go.sum, mods/server/server.go, mods/server/svrconf.hcl
=> http token based authentication for client

.github/workflows/ci-pr.yml, go.mod, go.sum, mods/server/mgmt_key.go, mods/server/mgmt_key_test.go, mods/server/server.go, mods/server/svrconf.hcl, mods/server/svrkey.go, mods/server/svrkey_test.go
=> mqtt tls and authentication

go.mod, go.sum, main/machbase-neo/main.go, mods/server/server.go
shell preferences
- box-style
- server
- timeformat
- tz
- vi-mode
=> apply neo-shell preferences

README.md, mods/server/server.go, mods/service/security/auth_svr.go, mods/service/sshsvr/sshd/sshd.go, mods/service/sshsvr/sshsvr.go
=> refactoring repo structure

mods/expression/parse.go, mods/tql/fm_bytes.go, mods/tql/fm_context.go, mods/tql/fm_monad_test.go, mods/tql/fx_definitions.go, mods/tql/fx_generate.gen.go, mods/tql/task.go, mods/tql/task_node.go, mods/tql/task_test.go
use `context()` instead of `CTX`
`payload()` for `CTX.Body`
`key()` for `K`
`value()` for `V`
`param("variable")` for `$variable`
=> CTX, K, V deprecated

mods/codec/opts/generate.gen.go, mods/tql/fm_encoder.go, mods/tql/fx_generate.gen.go, mods/tql/task_test.go
encoder leads server crash by malicious argument
=> fix crash by malicious arguments of encoder

mods/codec/opts/generate.gen.go, mods/tql/fm_time.go, mods/tql/fx_definitions.go, mods/tql/fx_generate.gen.go, mods/util/types.go, mods/util/types_test.go
timeformatter
- timeformat()
- sqlTimeformat()
- ansiTimeformat()
=> support timeformatter

mods/do/lineprotocol.go
line protocol bind error bug fix
=> line protocol bind error bug fix

mods/args/args.go, mods/args/args_test.go, mods/args/help_test.go, mods/args/serve.go, mods/server/server.go
new starting option
--preset=auto (default)
--preset=edge
--preset=fog
=> serve --preset option

mods/codec/opts/generate.gen.go, mods/tql/fm_monad.go, mods/tql/fx_definitions.go, mods/tql/fx_generate.gen.go, mods/tql/task_test.go
Add TQL function 
- PUSHVALUE
- POPVALUE
- MAPVALUE
=> pushvalue, mapvalue, popvalue

.github/workflows/neo-regress.yml
change trigger cron time
add label
=> update action neo-regress.yml 

mods/tql/fm_monad.go, mods/tql/fx_definitions.go, mods/tql/fx_generate.gen.go, mods/tql/task_test.go
=> add group quantile

mods/service/httpd/m_read.go, mods/service/httpd/m_read_test.go, mods/service/httpd/m_write.go, mods/service/httpd/m_write_test.go
add, rows.Close()
delete, io.ReadAll( request.Body )
modify, lake current api query
=> lake api update

go.mod, go.sum, mods/bridge/internal/nats/natsbridge.go, mods/bridge/registry.go, mods/bridge/types.go, mods/model/bridgedef.go, mods/scheduler/registry.go, mods/scheduler/sched_subs.go, mods/shellV2/internal/cmd/bridge.go, mods/shellV2/internal/cmd/subscriber.go
=> nats bridge

mods/scheduler/registry.go
=> update subscriber autoStart

mods/codec/opts/generate.gen.go, mods/server/server.go, mods/service/httpd/h_tql.go, mods/service/security/auth_svr.go, mods/tql/fm_fake.go, mods/tql/fm_monad.go, mods/tql/fm_shell.go, mods/tql/fx_definitions.go, mods/tql/fx_generate.gen.go, mods/tql/task.go
- FAKE(onece(value)) 
- SHELL("show", "tables")
=> tql SELL() function

mods/service/backupd/backupd.go
=> update mount ' '

mods/tql/fm_csv.go
added code for csv.gz loading in TQL
=> support csv.gz files 

mods/tql/fm_csv.go, mods/tql/fx_definitions.go, mods/tql/fx_generate.gen.go, mods/tql/task_test.go
Loadign message 추가했습니다.
머지되면,  닫습니다.
=> loading message added

booter/functions.go, mods/server/server.go, mods/server/svrconf.hcl, mods/util/osutils_unix.go, mods/util/osutils_windows.go, mods/util/split_test.go
=> unix socket listener path flags

api/machcli/machcli.go, mods/util/split.go, mods/util/testdata/splitter_sql_1.json, mods/util/testdata/splitter_sql_1.sql
=> sql comment

api/machcli/machcli.go, api/machcli/machcli_test.go, api/machcli/pool.go, api/machcli/pool_test.go, api/machsvr/mach_grpc.go, api/machsvr/machsvr_test.go, api/testsuite/all_test.go, api/testsuite/tagtable.go, api/testsuite/testsuite.go, mods/args/args.go, mods/args/help.go, mods/args/serve.go, mods/args/svc_windows.go, mods/server/http.go, mods/server/http_opts.go, mods/server/server.go, mods/server/svrconf.go, mods/server/svrconf.hcl, mods/server/svrmetric.go, mods/server/svrmgmt.go, mods/server/svrnavel.go, mods/server/svrshells.go, test/linear/linear.go
This pull request includes significant changes to the `api/machcli` package, focusing on improving database connection handling, adding a connection pool, and enhancing the appender functionality. Additionally, it includes modifications to the `api/machsvr` package to support these changes. The most important changes are summarized below:
* Added new fields `MaxOpenConns`, `MaxOpenConnsFactor`, and `TrustUsers` to the `Config` struct to manage database connections and trusted users (`api/machcli/machcli.go`).
* Updated the `NewDatabase` function to initialize the new fields and set the maximum number of open connections based on CPU count and a configurable factor (`api/machcli/machcli.go`).
* Implemented `SetMaxOpenConns` and `MaxOpenConns` methods to manage the maximum number of open …
=> Work head modes

go.mod, mods/tql/fm_script.go, mods/tql/fm_script_es6.go
This pull request includes several changes to the `go.mod` and `mods/tql/fm_script.go` files. These changes primarily focus on adding support for ES6 JavaScript and updating dependencies.
Dependency updates:
* Added `github.com/dop251/goja v0.0.0-20230122112309-96b1610dd4f7` to the `require` section in `go.mod`.
* Removed `github.com/dop251/goja v0.0.0-20230122112309-96b1610dd4f7` from the indirect dependencies in `go.mod`.
Enhancements to JavaScript support:
* Introduced a new boolean variable `js_is_es6` to check for ES6 support based on a pragma flag in the `fmScript` function.
* Modified the `fmScript` function to handle the "es6" script type and use the `goja` engine for ES6 scripts. [[1]](diffhunk://#diff-a564fd397232ceefcacacfbb4707c89425fc7f9425bd095cb4dafbcff9c8e780L56-R63) …
=> add script

mods/tql/fm_script_es6.go, mods/tql/fm_script_test.go
This pull request introduces a new numerical function for Fast Fourier Transform (FFT) in the `mods/tql/fm_script_es6.go` file and adds corresponding tests in `mods/tql/fm_script_test.go`. The key changes include importing the necessary FFT module, adding the FFT function to the Goja context, and creating test cases to ensure the functionality works as expected.
* [`mods/tql/fm_script_es6.go`](diffhunk://#diff-2c6dcaed15cb3030a95ce4d854d944d428512edd7f157f4d984cd745d4eedfbcR19): Imported the FFT module to support numerical operations.
* [`mods/tql/fm_script_es6.go`](diffhunk://#diff-2c6dcaed15cb3030a95ce4d854d944d428512edd7f157f4d984cd745d4eedfbcR170-R171): Added the `num` function to the Goja context, which includes the FFT function.
* …
=> add FFT functionality to $.num() and corresponding tests

mods/codec/internal/geomap/leafletobj.go, mods/tql/fm_script_modules.go, mods/tql/fm_script_test.go, mods/tql/tql_test.go
This pull request introduces enhancements to the `ConvCoordinates` and `MarshalJS` functions in `leafletobj.go` to handle additional data types, improves error handling for unknown types in `MarshalJS`, and updates test cases in `tql_test.go` to reflect a module rename. Below are the key changes grouped by theme:
* Extended `ConvCoordinates` to support additional cases: `*[]float64`, `[2]float64`, `*[2]float64`, and `[][2]float64`, ensuring compatibility with more coordinate data formats. (`mods/codec/internal/geomap/leafletobj.go`, [mods/codec/internal/geomap/leafletobj.goR101-R131](diffhunk://#diff-38061c9c54267b2299e43a6acb12d409d2747202ef07aba00516d58b92fd76b8R101-R131))
* Updated `MarshalJS` to handle new data types (`*[]float64`, `[2]float64`, `*[2]float64`) for consistent …
=> native modules for analytics

api/machcli/machcli.go, go.mod, go.sum, mods/bridge/connector/connector.go, mods/jsh/builtin/builtin.go, mods/jsh/builtin/jsh.js, mods/jsh/filter/filter_test.go, mods/jsh/http/client.go, mods/jsh/http/http.go, mods/jsh/http/http_test.go, mods/jsh/http/listener.go, mods/jsh/http/router.go, mods/jsh/http/test/html/hello.txt, mods/jsh/http/test/html/index.html, mods/jsh/jsh.go, mods/jsh/jsh_test.go, mods/jsh/mqtt/mqtt.go, mods/jsh/mqtt/mqtt_test.go, mods/jsh/process.go, mods/jsh/service.go, mods/jsh/system/system.go, mods/jsh/system/system_test.go, mods/server/http.go, mods/server/mqtt.go, mods/tql/tql_test.go
This pull request introduces significant enhancements to the HTTP module in the `jsh` package, refactors existing code for better modularity, and updates dependencies. The most notable changes include the addition of a new `http.Client` implementation, improvements to test coverage, and updates to the Kalman filter test cases to handle timestamp parsing more explicitly.
* Added a new `http.Client` implementation to support HTTP requests with configurable headers, methods, and callbacks. This includes methods for handling responses in various formats (e.g., JSON, CSV, text). (`mods/jsh/http/client.go`, [mods/jsh/http/client.goR1-R229](diffhunk://#diff-7d0e1b7d9fe28fdb3e01219322e0d4f7ec6b4014514be9f6c8c7c34414fb2615R1-R229))
* Refactored `http.request` functionality into a dedicated …
=> http server
